Add InfEdit to image editing pipelines
TIGER-AI-Lab/ImagenHub pull request #21
Opened 2024-04-19 20:49 UTC by h6kplus

# What does this PR do?

Add the implementation of InfEdit (CVPR 2024, https://sled-group.github.io/InfEdit/)

## Modification

Add Infedit to infermodel._init_
create infedit.py in infermodel
create pipeline foler infedit in pipelines

2024-04-20 22:55 UTC, vinesmsuic requested changes
Hi, thank you for much for the contribution! Just need a minor modfication on docstring.

2024-04-20 22:55 UTC, vinesmsuic commented on src/imagen_hub/infermodels/infedit.py
> +    """
need update for docstring

2024-04-21 14:19 UTC, h6kplus commented
Updated!

2024-04-21 15:37 UTC, vinesmsuic approved these changes
LGTM, thanks for the contribution!

2024-04-21 15:37 UTC, merged